### ISSUE TITLE
文档错误

### ISSUE THREAD

**Issue by liyuchuan86** [SuperMap/vue-iClient3D#1]
文档中说明需要引入 import 'vue-iclient3d/index.css'  实际上地址应该是 import 'vue-iclient3d/lib/index.css'

**Comment by supermapliukaiyun** [comment]
已经进行了更新  如你在使用过程中有更好的建议，请多多指出

**Comment by liyuchuan86** [comment]
https://www.supermapol.com/earth/vue-react-iclient3d-docs/zh/api/guide/quick-start.html   这个文档里面还没有更新噢

**Comment by supermapliukaiyun** [comment]
已修改
