### ISSUE TITLE
照教程运行错误

### ISSUE THREAD

**Issue by liyuchuan86** [SuperMap/vue-iClient3D#2]
![Snipaste_2022-06-28_13-58-56](https://user-images.githubusercontent.com/32632734/176104409-6d83dbff-2ef0-456a-8143-8993d6698868.jpg)

**Comment by supermapliukaiyun** [comment]
这个报错是 引入SuperMap3D.js报错，不影响运行吧，内部已经记录了这个问题，在修复中

**Comment by liyuchuan86** [comment]
因为这个错误根本无法运行呀，怎么就关闭了

**Comment by supermapliukaiyun** [comment]
这个报错不影响代码运行，你在看下 是否是其他问题。或者粘贴下代码看下
